### PR TITLE
Add German translation (untested)

### PR DESCRIPTION
**Pull request by Wuzzy2**
Well, I was bored and translated the game into German. :D

I hope it is useful for the project.
WARNING: This translation is NOT tested (but it was proofread), because I don't know how to test a translation and I have not found documentation explaining how to do so.
So expect some strings which are too long and other potential problems.

[Review on Reviewable](https://reviewable.io/reviews/christopho/zelda_roth_se/90)

### CODE REVIEW

**Comment by christopho** [comment]
Thanks!
It seems to work, except capitalized letters that have an umlaut. They need to be added to the fonts/alttp.png file.
Also as expected, a few strings exceed their maximum space in some menus.

**Comment by Diarandor** [comment]
Hi! Is someone working in the spanish translation? I think I could do it these holidays if you want.

**Comment by christopho** [comment]
@Diarandor Not that I am aware of :)

**Comment by Diarandor** [comment]
Ok. Then I will try to do it for the next month, during my holidays.

**Pull request merged**
